global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama-exporter:9100']

  - job_name: 'mcp-servers'
    static_configs:
      - targets:
        - 'github-mcp:3001'
        - 'github-chat-mcp:3002'
        - 'gitlab-mcp:3003'
        - 'memory-mcp:3004'
        - 'basic-memory-mcp:3005'
        - 'time-mcp:3006'
        - 'wolfram-alpha-mcp:3007'
        - 'discord-mcp:3008'
        - 'fetch-mcp:3009'
        - 'inspector-mcp:3010'
        - 'sequential-thinking-mcp:3011'
        - 'puppeteer-mcp:3012'
        - '3d-printer-mcp:3013'
        - 'desktop-commander-mcp:3014'
        - 'ollama-mcp-bridge:3015'