version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=n8n
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - N8N_URL=http://n8n:5678
      - N8N_API_KEY=${N8N_API_KEY:-}
      - MCP_SERVER_PORT=3000
      - MCP_SERVER_HOST=0.0.0.0
    depends_on:
      - n8n
    networks:
      - n8n-network
    command: python src/n8n-mcp-server.py

  setup:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - N8N_URL=http://n8n:5678
      - N8N_USER=admin
      - N8N_PASSWORD=password
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - OPENPROJECT_URL=${OPENPROJECT_URL:-}
      - OPENPROJECT_TOKEN=${OPENPROJECT_TOKEN:-}
    depends_on:
      - n8n
    networks:
      - n8n-network
    volumes:
      - ./.env:/app/.env
    command: >
      bash -c "
        echo 'Waiting for n8n to start...' &&
        sleep 30 &&
        python setup.py install --env-file .env --no-install
      "

volumes:
  n8n_data:

networks:
  n8n-network:
    driver: bridge
