version: '3.8'

services:
  llm-cost-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - llm-cost-analyzer-network

networks:
  llm-cost-analyzer-network:
    driver: bridge