version: '3.8'

services:
  llm-cost-analyzer-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MCP_ENABLED=true
      - MCP_SERVER_ID=llm-cost-analyzer
      - MCP_SERVER_NAME=LLM Cost Analyzer
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp-network
    driver: bridge