apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  labels:
    app: mcp-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
      - name: mcp-inspector
        image: mcp/inspector:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: PORT
          value: "8080"
        - name: MCP_SERVERS
          value: "filesystem-mcp:3001,desktop-commander-mcp:3002,sequential-thinking-mcp:3003,github-chat-mcp:3004,github-mcp:3005,puppeteer-mcp:3006,basic-memory-mcp:3007,wikipedia-mcp:3008"
        - name: LOG_LEVEL
          value: "info"
        - name: REFRESH_INTERVAL
          value: "30"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector
spec:
  selector:
    app: mcp-inspector
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer