name: OpenHands Issue Resolver

on:
  issues:
    types: [opened, labeled, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  resolve:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'fix-me')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@openhands-agent')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@openhands-agent'))
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install OpenHands
        run: pip install openhands-agent
      
      - name: Run OpenHands Issue Resolver
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL || 'anthropic/claude-3-5-sonnet-20241022' }}
          LLM_BASE_URL: ${{ secrets.LLM_BASE_URL || '' }}
          OPENHANDS_MAX_ITER: ${{ vars.OPENHANDS_MAX_ITER || '10' }}
          OPENHANDS_MACRO: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
          TARGET_BRANCH: ${{ vars.TARGET_BRANCH || 'main' }}
        run: |
          openhands-agent resolve \
            --repo ${{ github.repository }} \
            --issue ${{ github.event.issue.number || github.event.pull_request.number }} \
            --platform github